import { Injectable } from '@angular/core';
import { HttpRequest, HttpHandler, HttpEvent, HttpInterceptor } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable()

export class JwtInterceptor implements HttpInterceptor {
    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        
    // add authorization header with jwt token if available
    if(localStorage.getItem('token')){
        let tokenRecived = localStorage.getItem('token');

            //remove quotes generated by angular storage
            if (tokenRecived) {
                tokenRecived = tokenRecived.replace(/^"(.*)"$/, '$1'); // Remove quotes from token start/end. This is a temp fix?!
            }
            request = request.clone({
                setHeaders: {
                    'Content-Type' : 'application/json; charset=utf-8',
                    'Accept'       : 'application/json',
                    'Authorization': 'Bearer ' + tokenRecived
                }
            });
        }

        return next.handle(request);
    }
    
}